### ISSUE TITLE
License issue of the generated files

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-docc-render#271]
### Issue Description

Someone found that every third party library using swift-docc to generate Github docs page will have the swift-project license description stating that "source file is part of the Swift.org open source project".

Is this the intended license behavior for swift-docc-render?

![twitter_FSJL1EeagAAo7Ch](https://user-images.githubusercontent.com/43724855/167255110-255e9a64-7b12-4912-8fd5-23f084784e3c.jpg)

> https://twitter.com/kemchenj/status/1522864497253556224?s=21&t=_6mJY0oBP5Gudw_GrlosLw
> [Eng translation]:
> I suddenly found this copyright description in the web page HTML / JS / CSS generated by swift docc.
> Is it reasonable for the web static generator to insert this content into the file? So these pages suddenly belong to Apple Inc?
> Anyone to explain this?

### Expected behavior

The generated html file should not add the license info since most of its content is not created by Apple Inc. or swift-docc-render.

The CSS, JS, svg and other resource files is OK to be marked with the license info as far as I see.

### Other consideration

swift-docc will look for DOCC_HTML_DIR to get the index.html file. And if the env is not provided, it will use the fallback default location( @exec/../share/docc/render) which for most case the Xcode toolchain location.

The 3rd party library maintainer can opt-out this license issue by using their custom render resource.

But I think even using the default one we should not add such license info to index.html file.

### Related file
- swift-docc
https://github.com/apple/swift-docc/blob/e761687057fd72949bfbc5579781b4a8e0adb653/Sources/SwiftDocCUtilities/ArgumentParsing/Options/TemplateOption.swift#L80-L104

- swift-docc-render
https://github.com/apple/swift-docc-render/blob/68d86b2070c38a6e45274d8988cbd5324987e926/src/setup-utils/license-header-built-files.js#L14-L20

**Comment by sofiaromorales** [comment]
https://groue.github.io/GRDBQuery/0.3/documentation/grdbquery/

**Comment by mportiz08** [comment]
This is an interesting issue, and we're going to follow up with the appropriate legal experts to decide how to resolve this. There may be a small delay in getting the resolution, but we agree that it is important to address this.

Thanks for bringing this to our attention @Kyle-Ye!

**Comment by mportiz08** [comment]
We have followed up on this and agreed to remove this license description from the generated HTML files.

Thanks again for creating this issue!

**Comment by groue** [comment]
Thank you @mportiz08. Seeing [my prose](https://groue.github.io/GRDBQuery/0.3/documentation/grdbquery/gettingstarted) with a different licence than [intended](https://github.com/groue/GRDBQuery/blob/main/LICENCE) was indeed surprising. Thank you @Kyle-Ye for doing the initial report 👍
