### ISSUE TITLE
[SR-16120] Navbar dropdown chevron icon not showing 

### ISSUE THREAD

**Issue by sofiaromorales** [apple/swift-docc-render#272]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16120      |
   |Radar             | None         |
   |Original Reporter | @sofiaromorales      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Safari 15.3  
Testing locally using \`swift-docc-render\` repo with HEAD in commit id 6471e29

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC-Render    |
   |Labels            | Bug        |
   |Assignee          | @sofiaromorales      |
   |Priority          | Medium      |

   

   md5: 538d9691ff42c6199dc4eb4d61b32ed0

  </details>

**Issue Description:**

In certain viewports, and zoom levels in Safari, when in collapse range the chevron icon from the dropdown menu is disappearing. The element still exists and it can be clicked but the \`:before\` and \`:after\` elements aren't visible.

Steps to reproduce:  
1. Open \`http://localhost:8080/documentation/slothcreator\`  
2. In Safari select Develop \> Open Responsive Design Mode  
3. Select viewport 800 x 700 resolution 1x  
4. Zoom out to 85% (clicking once \`⌘ -\`)

**Comment by mportiz08** [comment]
I believe this was addressed by #179
