### ISSUE TITLE
[SR-15904] Navigator sidebar scrolling is broken on mobile

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc-render#275]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15904      |
   |Radar             | rdar://88723982         |
   |Original Reporter | @ethan-kusters      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC-Render    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: da870d5f22d024460b30e14598c46764

  </details>

**Issue Description:**

Per <https://forums.swift.org/t/new-swift-docc-content-styling/55326/7> it seems there are issues with the new navigator sidebar scrolling correctly on mobile devices.

**Comment by mportiz08** [comment]
I believe this was resolved before the feature was first merged behind a feature flag with #51
