### ISSUE TITLE
[SR-15903] "No overview available" text appears on pages that have a defined abstract

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc-render#276]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15903      |
   |Radar             | rdar://problem/89641502         |
   |Original Reporter | @ethan-kusters      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC-Render    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 81da10097df893b263dc8d51117492bf

  </details>

**Issue Description:**

The "No overview available" text has started appearing in DocC-Render even on pages that have a defined abstract. This seems to be a regression related to the navigator changes.

Current argument-parser: <https://apple.github.io/swift-argument-parser/documentation/argumentparser/completionkind/shellcommand(_:)/>

Argument-parser with navigator changes: <https://ethan-kusters.github.io/swift-argument-parser/documentation/argumentparser/completionkind/shellcommand(_:)/>

**Comment by mportiz08** [comment]
I believe this has since been addressed and resolved with #113
