### ISSUE TITLE
Bug - View not scrollable when accessing from sidebar navigator

### ISSUE THREAD

**Issue by sofiaromorales** [apple/swift-docc-render#293]
**Describe the bug**

When using the full-width sidebar navigator, if an item that redirects to a new route different from the current one gets selected, the sidebar gets dismissed, but the scrolling inside the selected page doesn't work.

**Expected behavior**

When an item in the full-width sidebar navigator gets selected, the sidebar should get dismissed, and the view should be scrollable if the body content is higher than the VP.

**Steps to reproduce**

1. Open a `.doccarchive` with sidebar navigator enabled and a tutorials page
2. In Safari, select Develop -> Open Responsive Design Mode  and select an iPhone size (or any other VP in collapse range) 
3. Open the sidebar navigator
4. Select `Meet SlothCreator` or any other tutorial item
5. Once on the tutorials page, try to scroll the page

**Related file**

In `src/components/AdjustableSidebarWidth.vue` there's a method that locks/unlocks the view scroll adding some fixed values to the `body` element.

```js
// src/components/AdjustableSidebarWidth.vue
toggleScrollLock(lock) {
     ...
      if (!scrollLockContainer) return;
      if (lock) {
        scrollLock.lockScroll(scrollLockContainer);
        ...
      } else {
        scrollLock.unlockScroll(scrollLockContainer);
        ...
      }
}
```  
On a relative path change, the scroll gets unlocked, but since the tutorial items redirect to a new route, with path `/tutorials/`, the `AdjustableSidebarWidth` component is removed from the DOM and the `scrollLockID` element id is not found, keeping the lock on.
 
```js
// src/components/AdjustableSidebarWidth.vue
this.$once('hook:beforeDestroy', () => {
      ...
      if (this.openExternally) {
        this.toggleScrollLock(false);
      }
});
```

A possible solution could be to not require `scrollLockID` to unlock the scroll.

**Environment**

Safari 15.3
Testing locally using `swift-docc-render` repo with HEAD in commit id 47b17909e440161619de31d369eeb5dfa0c55ff6 

**Attachment**

![Screen Shot 2022-05-11 at 11 45 28 PM](https://user-images.githubusercontent.com/49292858/167989886-f52d03c2-e375-4140-9a40-ce08b536d7dc.png)

**Comment by dobromir-hristov** [comment]
Great catch!
