### ISSUE TITLE
> 1) In small viewports the tag "Hide deprecated" gets cut off when being selected. I'm pretty sure this is a regression from https://github.com/apple/swift-docc-render/pull/

### ISSUE THREAD

**Issue by JCDiana** [apple/swift-docc-render#342]
> 1) In small viewports the tag "Hide deprecated" gets cut off when being selected. I'm pretty sure this is a regression from https://github.com/apple/swift-docc-render/pull/291
> 
> Do you want to fix it in this radar or want me to create a new one?
> 
> 
> 
> <img width="367" alt="Screenshot 2022-05-30 at 17 16 08" src="https://user-images.githubusercontent.com/8567677/171022151-b0a1de97-a2f6-4885-905f-816fdba2ce24.png">
> 
> 
> 
> 2) When adding an input to filter input after selecting the "Hide deprecated" tags, the matching children don't get opened, is this intended? I thought we would keep it closed only when there was no input added.
> 
> 
> 
> <img width="365" alt="Screenshot 2022-05-30 at 17 18 45" src="https://user-images.githubusercontent.com/8567677/171022541-af798dac-3048-44be-b7fc-f7134df1ff35.png">

__Originally posted by @JCDiana in https://github.com/apple/swift-docc-render/pull/331#issuecomment-1141408547__

**Comment by dobromir-hristov** [comment]
We have fixed these issues in the PR. The cutoff tag is expected.
