### ISSUE TITLE
Anchor for section titles for quick sharing of sections

### ISSUE THREAD

**Issue by marinaaisa** [apple/swift-docc-render#394]
### Feature Name

Anchor for section titles for quick sharing of sections

## Summary
Add anchor for section titles for quick sharing of sections.
Example from https://vuejs.org/guide/introduction.html#what-is-vue

### For desktop version:
Anchor will show when user hovers the title section.

### For mobile version:
Anchor will show when user clicks in the title section.

## AX considerations
Anchor will have an aria-label called "Go to [name-of-section] section".

### Motivation

Currently, it's difficult to share a section from the page. This anchor allows users to navigate to those sections and be able to select from the URL, copy and share that section only.

### Importance

It improves sharing features.

### Alternatives Considered

None

**Comment by mportiz08** [comment]
@marinaaisa I think this may be a dupe of #273, right?

**Comment by dobromir-hristov** [comment]
Yep, looks like it.

**Comment by marinaaisa** [comment]
Closed in favor of https://github.com/apple/swift-docc-render/issues/273
