### ISSUE TITLE
[Quick Navigation] When typing in the filter bar, pressing '/' incorrectly shows the Quick Navigation modal

### ISSUE THREAD

**Issue by franklinsch** [apple/swift-docc-render#410]
### Description

When using the navigator filter bar to look up a symbol, pressing '/' probably shouldn't invoke the modal if you're actually looking for a symbol with the `/` character within in. Maybe when the filter bar is focused, '/' shouldn't invoke the Quick Navigation modal at all.

### Checklist

- ~[ ] If possible, I've reproduced the issue using the `main` branch of this package.~ N/A, this was reproduced using a WIP demo https://sofiaromorales.github.io/swift-argument-parser/documentation/argumentparser
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Steps To Reproduce

1. Navigate to https://sofiaromorales.github.io/swift-argument-parser/documentation/argumentparser
2. Start typing in the navigator sidebar's filter bar.
3. Enter '/'

**Comment by mportiz08** [comment]
\cc @sofiaromorales

**Comment by ethan-kusters** [comment]
@franklinsch @sofiaromorales can we close this out?
