### ISSUE TITLE
[Quick Navigation] Quick Navigation modal doesn't resize on narrower viewports

### ISSUE THREAD

**Issue by franklinsch** [apple/swift-docc-render#411]
### Description

On narrower viewports (but still larger than mobile), the modal is clipped (see screenshot below).

<img width="686" alt="Screenshot 2022-08-11 at 09 46 17" src="https://user-images.githubusercontent.com/7278429/184096887-f837135a-2f0b-4fe7-b791-50462198e3a9.png">
 

### Checklist

~- [ ] If possible, I've reproduced the issue using the `main` branch of this package.~ N/A, I reproduced this on a WIP demo https://sofiaromorales.github.io/swift-argument-parser/documentation/argumentparser
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Steps To Reproduce

1. Navigate to https://sofiaromorales.github.io/swift-argument-parser/documentation/argumentparser/
2. Invoke Quick Navigation
3. Reduce your viewport size to something narrow

**Comment by mportiz08** [comment]
\cc @sofiaromorales

**Comment by sofiaromorales** [comment]
addressed by  #396

**Comment by Kyle-Ye** [comment]
> addressed by #396

Can we add the issue's development to #396 and close this issue? @sofiaromorales

**Comment by sofiaromorales** [comment]
> > addressed by #396
> 
> Can we add the issue's development to #396 and close this issue? @sofiaromorales

This bug was resolved in #396, but only a project maintainer can close the issue \cc @mportiz08
