### ISSUE TITLE
Add a 'copy code to clipboard' button for code blocks

### ISSUE THREAD

**Issue by byaruhaf** [apple/swift-docc-render#449]
The swift book has a number of code blocks to complement the explanations.
To improve the experience for the reader we should add a “copy code” button to make it simple for them to copy and paste the code.

**Comment by natikgadzhi** [comment]
Related: https://github.com/apple/swift-docc/issues/737

Both in code blocks — if someone wanted to make two improvements with one PR ;)

**Comment by mportiz08** [comment]
Thanks for the suggestion @byaruhaf. I believe we are already tracking this enhancement request in #274
