### ISSUE TITLE
[Quick Navigation] Pages that are curated multiple times appear duplicated in search results

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc-render#489]
### Description

Searching for "defining" in [ArgumentParser](https://staging.swiftpackageindex.com/apple/swift-argument-parser/main/documentation/argumentparser) produces duplicated results:

<img width="1436" alt="Screenshot 2022-12-04 at 10 13 38 AM" src="https://user-images.githubusercontent.com/6750147/205508132-468156d2-7824-4c3c-a976-0a7063b3a1bc.png">

This is likely because that page appears twice when filtering in the navigator:

<img width="1436" alt="Screenshot 2022-12-04 at 10 15 20 AM" src="https://user-images.githubusercontent.com/6750147/205508157-b97cb5b7-f9c8-4ad8-8b8a-84ef4daa3a55.png">

Because it's curated by the documentation author on both the top-level page and as a child of the `ParsableCommand` symbol. For the purposes of Quick Navigation, we should filter out duplicate results like this.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Expected Behavior

I would expect that each page only appears once in the Quick Navigation search results.

### Actual behavior

The "Defining Commands and Subcommands" page appears twice.

### Steps To Reproduce

1. Navigate to https://staging.swiftpackageindex.com/apple/swift-argument-parser/main/documentation/argumentparser
2. Search "defining"

**Comment by ethan-kusters** [comment]
CC: @sofiaromorales @marinaaisa

**Comment by dobromir-hristov** [comment]
Even though its the same page, it is unique because it has different parents, at diff levels and so on, so its UID is diff. 

I guess at the last step, where we slice off the first 20 items, we could check for uniqueness by the URL?

**Comment by sofiaromorales** [comment]
> I guess at the last step, where we slice off the first 20 items, we could check for uniqueness by the URL?

+1 to this, we can filter them by URL uniqueness and keep the top-level one
