### ISSUE TITLE
[Quick Navigation] Previously searched text should be selected when re-opening Quick Navigation

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc-render#490]
### Description

Previously searched text should be selected when re-opening Quick Navigation. When using tools like Spotlight and Xcode's Open Quickly, I expect to always be able to activate the search panel and immediately begin typing my new query. Currently in DocC-Render, I have to manually delete my prior query before beginning a new one. The solution to this problem in Xcode and macOS is to always select the previously searched text.

https://user-images.githubusercontent.com/6750147/205508410-1c57661d-803b-4086-a933-9c84ae196041.mov

https://user-images.githubusercontent.com/6750147/205508521-a05f933e-a8a4-4c13-9373-455fbae13c61.mov

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Expected Behavior

I expect to always be able to activate the search panel and begin typing a new query without worrying about the prior one.

### Actual behavior

I have to delete any existing text in the Quick Navigation box from my previous query.

### Steps To Reproduce

1. Open https://staging.swiftpackageindex.com/apple/swift-argument-parser/main/documentation/argumentparser
2. Press Shift+Cmd+O and type "test"
3. Hit enter to navigate to "Manual Parsing and Testing"
4. Read that page for a bit or maybe leave that tab entirely and come back to it.
5. Decide to look for information on the "command" protocol
6. Press Shift+Cmd+O and type "command"

---

Instead of Quick Navigation reading "command" it reads "testcommand"

**Comment by ethan-kusters** [comment]
CC: @sofiaromorales @marinaaisa

**Comment by marinaaisa** [comment]
Hi @ethan-kusters , I agree, we could add this feature to improve the UX when searching again. Is there any radar associated to this issue? In case of no, could you open it please? Thanks!
