### ISSUE TITLE
Symbol links with custom authored titles are rendered in code voice

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc-render#632]
### Description

Symbol links with custom authored titles are rendered in code voice

If I write a doc link with a title like

```
Check out [this great function](doc:Sloth/eat(_:quantity:)).
```

the rendered output is

```
Check out `this great function`.
```

With `this great function` in code voice. The custom title should respect the formatting that was provided in the link title.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Swift-DocC Version Information

88d0fd6676f2a2ee2d169d813420645cf6bfd52d

**Comment by mportiz08** [comment]
Sounds reasonable, although I worry a bit about there being an expectation that a link to a symbol would be in code voice by default. I think this is probably the right way to go though since it allows for that flexibility.

I didn't even realize you could provide a custom title for a DocC symbol link now 😮

**Comment by Kyle-Ye** [comment]
> Sounds reasonable, although I worry a bit about there being an expectation that a link to a symbol would be in code voice by default. I think this is probably the right way to go though since it allows for that flexibility.
> 
> I didn't even realize you could provide a custom title for a DocC symbol link now 😮

This feature is tracked as a bug via https://github.com/apple/swift-docc/issues/271 and implemented by https://github.com/apple/swift-docc/pull/376 @mportiz08

**Comment by marinaaisa** [comment]
Hey @ethan-kusters @Kyle-Ye @mportiz08 I opened a PR for this issue: https://github.com/apple/swift-docc-render/pull/645
Symbol links now respect the formatting provided in `overridingTitleInlineContent` but this means that if overridingTitleInlineContent's type is other than `symbol` or `codeVoice` it won't be using CodeVoice component at all.

Is this expected as it is?
