### ISSUE TITLE
Hard breaks aren't reflected in output

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-docc-render#697]
### Description

See full issue here https://github.com/apple/swift-docc/issues/477

After https://github.com/apple/swift-docc/pull/633, swift-docc will emit LineBreak from swift-markdown into "\n". But swift-docc-render still does not treat the new line correctly.

<img width="1724" alt="SCR-20230618-qoil" src="https://github.com/apple/swift-docc-render/assets/43724855/6a119f19-bb18-432b-a97d-516f703d7966">

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Expected Behavior

```
{
  "inlineContent": [
    {
      "text": "This text should",
      "type": "text"
    },
    {
      "text": "\n",
      "type": "text"
    },
    {
      "text": "appear on two lines.",
      "type": "text"
    }
  ],
  "type": "paragraph"
}
```

Render text in 2 lines

### Actual behavior

Render text in 1 line

### Steps To Reproduce

1. Use the following markdown input
```
let source = #"""
This text should\
appear on two lines.

This text should  
appear on two lines.

This is the second paragraph.
"""#
```

2. Use this version of docc https://github.com/apple/swift-docc/pull/633
3. Set VUE_APP_DEV_SERVER_PROXY to the corresponding .docc-build folder

**Comment by mportiz08** [comment]
I can help look into this. I'm thinking we would probably just want to map the inline text nodes with newline characters into `<br>` HTML elements.

I'll need to play with the DocC PR to see if we can rely on the newline always being in its own individual text node or if it could possibly be interspersed with other text.
