### ISSUE TITLE
Code listings with the `diff` language don't render green/red lines as they should

### ISSUE THREAD

**Issue by mportiz08** [apple/swift-docc-render#712]
### Description

The `diff` or `patch` language can be used to identify code listings for the appropriate syntax highlighting as documented in [Formatting Your Documentation Content](https://www.swift.org/documentation/docc/formatting-your-documentation-content#Add-Code-Listings) but the appropriate added/deleted lines are not displayed with any special colors like they should be.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Expected Behavior

* deleted lines should have a red background
* added lines should have a green background

### Actual behavior

The thunk headings do get an expected styling with a slightly different color but the added/deleted lines look like normal lines and have no special background color.

### Steps To Reproduce

1. Add a code listing like the following to your documentation:

```diff
diff --git a/1.txt b/2.txt
index de98044..6372083 100644
--- a/1.txt
+++ b/2.txt
@@ -1,3 +1,3 @@
 a
-b
 c
+d
```

2. Check the styling of lines that start with `-` or `+`

**Comment by ethan-kusters** [comment]
rdar://105420253
