### ISSUE TITLE
Blank articles when hosting DocC archives if library name is "Tutorials"

### ISSUE THREAD

**Issue by jiachenyee** [apple/swift-docc-render#722]
### Description

When hosting a DocC archive with a library named "Tutorials" (case insensitive) online, it results in a blank screen when trying to view articles. 

When an article is in the library, it hosts the article on a URL like this: "example.com/tutorials/articlename"

When trying to open it, it shows a blank screen.
![image](https://github.com/apple/swift-docc/assets/36725840/ec857874-ebe0-42b3-8ef7-4da665d248c7)

Here is a demo site: https://bug.jiachen.app/documentation/tutorials 
GitHub repository: https://github.com/jiachenyee/DemoDocCIssue/

I assume this somehow caused an issue with the way DocC hosts tutorials with a similar URL pattern, having tutorials on a URL like "example.com/tutorials/tutorialname".

I should point out that the article displays perfectly fine on Xcode, the only issue is when hosted online.

I have only had time to test it out with GitHub Pages and Xcode 14 Beta 4, but I assume the behaviour should be consistent regardless.

I have tested on multiple browsers, including Safari (Mac/iPhone), Chrome (Mac), and Firefox (Mac). The issue exists on all of them.

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

It should display the contents of the article file. Here is a screenshot of what is displayed when the DocC Archive is opened within Xcode.

![Sample Article  - Xcode  2023-07-23 at 10 20 44 PM](https://github.com/apple/swift-docc/assets/36725840/7a1a3556-3dc8-4533-b384-4ef8cb3cf6f5)

### Actual behavior

This is what it looks like when viewing the hosted version.

![image](https://github.com/apple/swift-docc/assets/36725840/102175f2-a981-49a8-84dc-cbdbf0e0c08b)

View it for yourself: https://bug.jiachen.app/documentation/tutorials/article

### Steps To Reproduce

1. Create a new Swift Package in Xcode
2. Name the Package "Tutorials"
3. Create a Documentation.docc Documentation Catalog
4. Create an article file 
5. Retrieve the DocC archive 
6. When previewing the .doccarchive from Xcode, it looks perfectly fine
7. When hosted on a platform like GitHub Pages (only tested with GH Pages), the article file shows up completely blank (example: https://bug.jiachen.app/documentation/tutorials/article/) 

I assume it might be because of DocC tutorials using "example.com/documentation/tutorials/xyz" and therefore, if a package is named "tutorials", it results in odd behaviours.

### Swift-DocC Version Information

Xcode 15 Beta 4

### Swift Compiler Version Information

```shell
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.10 clang-1500.0.29.1)
Target: arm64-apple-macosx14.0
```

**Comment by mportiz08** [comment]
It turns out to actually be an issue with the locale-prefixed tutorials route being too aggressive:

https://paths.esm.dev/?p=AAMeJbiAwQYY7IbAKdD5gRfAugICdhJwAdmknBMgoACBIdJlA9eMji_JKgBCGiSOMKhNUC2AAIqZdmQSEited-n94QkeB6UiUMvb3F1bIEqOj0wqCrmBTADk&t=/documentation/tutorials/article

In this scenario, the URL path `/documentation/tutorials/article` is actually getting resolved to the `/:locale?/tutorials/:id` route where "documentation" ends up as the `locale` 🥲

**Comment by mportiz08** [comment]
I wonder if maybe we can just switch the order of the routes so that the locale prefixed ones come later in the array instead of earlier than the main ones 🤔

**Comment by mportiz08** [comment]
Note to self: try swapping the order of the 2 splat expressions in [this array](https://github.com/apple/swift-docc-render/blob/d4b7889e2fee58e41759b2bcf6ee7a48650d81de/src/setup-utils/SwiftDocCRenderRouter.js#L22) to see if this resolves the routing issue here

**Comment by Kyle-Ye** [comment]
Add a new route `/documentation/tutorials/*` seems to fix the issue for me. (A tricky way to solve it) See #725

**Comment by mportiz08** [comment]
That technically works, but I think it would be preferable to avoid adding explicit routes for certain article names if possible.

I created an alternate PR to fix this that I think would be more correct, as it just adjusts the precedence of the routes in a way that is more optimal and fixes the rendering for this specific article name: #726
