### ISSUE TITLE
Meta descriptions do not include the contents of references

### ISSUE THREAD

**Issue by harlanhaskins** [apple/swift-docc-render#856]
### Description

This seems to be a bug in `extractFirstParagraphText` that it's not considering `InlineType.reference` nodes.

The contents of the first paragraph are extracted out and put into the `<meta name="description" content="<first paragraph>">`, but the logic ends up skipping over the contents of references. This means, for example that this page:

https://developer.apple.com/documentation/swiftui/view/upperlimbvisibility(_:)

Has this as their first paragraph:

> Sets the preferred visibility of the user’s upper limbs, while an [ImmersiveSpace](https://developer.apple.com/documentation/swiftui/immersivespace) scene is presented.

But the meta description is

```html
<meta name="description" content="Sets the preferred visibility of the user’s upper limbs, while an  scene is presented.">
```

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I would expect references to look up the appropriate title and use that title's text in the first paragraph.

### Actual behavior

Only inline text and paragraphs are considered.

### Steps To Reproduce

This bug is reproducing on the Apple developer site, one example I linked above as https://developer.apple.com/documentation/swiftui/view/upperlimbvisibility(_:).

**Comment by hcz** [comment]
The same problem persists in `` `code` `` blocks
Fixed in https://github.com/apple/swift-docc-render/pull/863

Tested on SwiftDocCRender docs, for example,`Component/BaseDropdown`
```javascript
/**
 * A basic dropdown component to use when a simple `select` element is sufficient.
 *
 * For more advanced usages, see ``DropdownCustom``
 */
 ```

**Comment by hcz** [comment]
@mportiz08 I'd be very grateful if you could take a look at the code in related PR https://github.com/apple/swift-docc-render/pull/863

**Comment by mportiz08** [comment]
Oh whoops, saw your comment after I saw your PR :P

Your change looks good to me, but it would be nice to consolidate both of our work in one PR since it's all related. Thanks for spotting that!
